fpath=("/Users/samwang/.oh-my-zsh/custom/completions" $fpath)

source "$HOME/dotfiles/zsh/path.zsh"
source "$HOME/dotfiles/zsh/omz.zsh"

source ~/.myalias
source ~/.myfunctions
source ~/.myenv

source "$HOME/dotfiles/zsh/tools.zsh"
eval "$(starship init zsh)"
