model = "gpt-5.4"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
default_mode_request_user_input = true
plan_mode_reasoning_effort = "high"
sandbox_mode = "workspace-write"
approvals_reviewer = "user"
approval_policy = "on-request"
model_context_window = 1000000
model_auto_compact_token_limit = 900000

[sandbox_workspace_write]
network_access = true

[features]
unified_exec = true
shell_snapshot = true
steer = true
multi_agent = true
prevent_idle_sleep = true
js_repl = true
guardian_approval = true

[notice]
hide_full_access_warning = true

[tui]
status_line = [
    "project-root",
    "git-branch",
    "model-with-reasoning",
    "five-hour-limit",
    "weekly-limit",
    "context-used",
]
theme = "two-dark"

[projects."/Users/samwang/dotfiles"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/workspace"]
trust_level = "trusted"

[projects."/Users/samwang/.config/superpowers"]
trust_level = "trusted"

[projects."/Users/samwang/.claude/skills"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/workspace/oh-my-opencode"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/20260309"]
trust_level = "trusted"

[projects."/Users/samwang/.config/opencode"]
trust_level = "trusted"

[projects."/Users/samwang/.gemini"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/workspace/my-magic-opencode"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/oh-my-opencode-slim"]
trust_level = "trusted"

[projects."/Users/samwang/.agents/skills"]
trust_level = "trusted"

[projects."/Users/samwang/.config/opencode/plugins"]
trust_level = "trusted"

[projects."/Users/samwang/.gemini/extensions"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/OpenSpec"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/20260313-2/scins-integration"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/workspace/oh-my-opencode-slim"]
trust_level = "trusted"

[projects."/Users/samwang/Downloads"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/planning-with-files"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/oh-my-opencode-medium"]
trust_level = "trusted"

[projects."/Users/samwang/.config/opencode/skills"]
trust_level = "trusted"

[projects."/Users/samwang/.codex/skills"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/switch-omo-config-json"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/workspace/oh-my-opencode-medium"]
trust_level = "trusted"

[projects."/Users/samwang/Softleader/api-trigger"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/workspace/my-loop-plugin"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/powerrangers"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/workspace"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/workspace/just-loop"]
trust_level = "trusted"

[projects."/Users/samwang/Softleader/kapok"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/cicd"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/opencode"]
trust_level = "trusted"

[projects."/Users/samwang/Softleader/Iris/Backend/iris-auth"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/cicd-iris/uat-jenkins-pipeline"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/jdk-java-helper"]
trust_level = "trusted"

[projects."/Users/samwang/Softleader/Jasmine-v3/Backend/fairybell-auth"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/hashline-plugin"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/todo-continuation-enforcer"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/just-loop"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/count"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/mantis-cli"]
trust_level = "trusted"

[projects."/Users/samwang/Softleader/scins-asi-cie"]
trust_level = "trusted"

[projects."/Users/samwang/Softleader/kapok-2"]
trust_level = "trusted"

[plugins."slack@openai-curated"]
enabled = true
