model = "gpt-5.4"
model_reasoning_effort = "medium"
model_context_window = 1000000
model_auto_compact_token_limit = 900000
personality = "pragmatic"
default_mode_request_user_input = true
plan_mode_reasoning_effort = "high"


[features]
unified_exec = true
shell_snapshot = true
steer = true
multi_agent = false
prevent_idle_sleep = true
js_repl = true

[notice]
hide_full_access_warning = true

[tui]
status_line = [
    "project-root",
    "git-branch",
    "model-with-reasoning",
    "five-hour-limit",
    "weekly-limit",
    "context-used",
]

[projects."/Users/samwang/dotfiles"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/workspace"]
trust_level = "trusted"

[projects."/Users/samwang/.config/superpowers"]
trust_level = "trusted"

[projects."/Users/samwang/.claude/skills"]
trust_level = "trusted"

[projects."/Users/samwang/Repo/workspace/oh-my-opencode"]
trust_level = "trusted"

[projects."/Users/samwang/tmp/20260309"]
trust_level = "trusted"

[projects."/Users/samwang/.config/opencode"]
trust_level = "trusted"
